apiVersion: "spec.keptn.sh/0.2.0"
kind: "Shipyard"
metadata:
  name: "shipyard-auto-remediation"
spec:
  stages:
  - name: "production"
    sequences:  
    - name: "remediation"
      triggeredOn:
        - event: "production.remediation.finished"
          selector:
            match:
              evaluation.result: "fail"
      tasks:
        - name: "get-action"
        - name: "action"
        - name: "evaluation"
          triggeredAfter: "5m"
          properties:
            timeframe: "5m"